# Generated by Django 4.1.5 on 2023-01-25 15:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test',
            field=tinymce.models.HTMLField(max_length=200),
        ),
    ]
