# Generated by Django 4.1.5 on 2023-01-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_test_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
